export declare const months: string[];
export declare const days: string[];
export { dateIntegerToDate } from './dateIntegerToDate.js';
export { dateStringToDate } from './dateStringToDate.js';
export { dateToInteger } from './dateToInteger.js';
export { dateToString } from './dateToString.js';
export { dateIntegerToString } from './dateIntegerToString.js';
export { dateStringToInteger } from './dateStringToInteger.js';
export { dateToTimeInteger } from './dateToTimeInteger.js';
export { dateToTimeString } from './dateToTimeString.js';
export { timeIntegerToString } from './timeIntegerToString.js';
export { timeStringToInteger } from './timeStringToInteger.js';
