import { dateIntegerToDate } from './dateIntegerToDate.js';
import { dateIntegerToString } from './dateIntegerToString.js';
import { dateStringToDate } from './dateStringToDate.js';
import { dateStringToInteger } from './dateStringToInteger.js';
import { dateToInteger } from './dateToInteger.js';
import { dateToString } from './dateToString.js';
import { dateToTimeInteger } from './dateToTimeInteger.js';
import { dateToTimePeriodString } from './dateToTimePeriodString.js';
import { dateToTimeString } from './dateToTimeString.js';
import { isValidDateInteger } from './isValidDateInteger.js';
import { isValidDateString } from './isValidDateString.js';
import { isValidTimeInteger } from './isValidTimeInteger.js';
import { isValidTimeString } from './isValidTimeString.js';
import { timeIntegerToPeriodString } from './timeIntegerToPeriodString.js';
import { timeIntegerToString } from './timeIntegerToString.js';
import { timeStringToInteger } from './timeStringToInteger.js';
export declare const months: string[];
export declare const days: string[];
export { dateIntegerToDate } from './dateIntegerToDate.js';
export { dateStringToDate } from './dateStringToDate.js';
export { dateToInteger } from './dateToInteger.js';
export { dateToString } from './dateToString.js';
export { dateIntegerToString } from './dateIntegerToString.js';
export { dateStringToInteger } from './dateStringToInteger.js';
export { dateToTimeInteger } from './dateToTimeInteger.js';
export { dateToTimeString } from './dateToTimeString.js';
export { dateToTimePeriodString } from './dateToTimePeriodString.js';
export { timeIntegerToString } from './timeIntegerToString.js';
export { timeIntegerToPeriodString } from './timeIntegerToPeriodString.js';
export { timeStringToInteger } from './timeStringToInteger.js';
export type { DateString, TimeString, TimePeriodString } from './dateTimeTypes.js';
export { isValidDateInteger } from './isValidDateInteger.js';
export { isValidDateString } from './isValidDateString.js';
export { isValidTimeInteger } from './isValidTimeInteger.js';
export { isValidTimeString } from './isValidTimeString.js';
declare const _default: {
    months: string[];
    days: string[];
    dateIntegerToDate: typeof dateIntegerToDate;
    dateIntegerToString: typeof dateIntegerToString;
    dateStringToDate: typeof dateStringToDate;
    dateToInteger: typeof dateToInteger;
    dateToString: typeof dateToString;
    dateStringToInteger: typeof dateStringToInteger;
    dateToTimeInteger: typeof dateToTimeInteger;
    dateToTimeString: typeof dateToTimeString;
    dateToTimePeriodString: typeof dateToTimePeriodString;
    isValidDateInteger: typeof isValidDateInteger;
    isValidDateString: typeof isValidDateString;
    isValidTimeInteger: typeof isValidTimeInteger;
    isValidTimeString: typeof isValidTimeString;
    timeIntegerToString: typeof timeIntegerToString;
    timeIntegerToPeriodString: typeof timeIntegerToPeriodString;
    timeStringToInteger: typeof timeStringToInteger;
};
export default _default;
